import type { Dispatch, RefObject, SetStateAction } from 'react';
import type { EffectiveLocale } from '../../lib/locale';
import type { PaneReplication, PaneReplicatedState } from '../../lib/paneSync';
import type { ActiveDocumentWatchTransport } from '../../lib/activeDocumentWatch';
import type { createDocumentSessionQueue, DocumentSessionQueueOperation, DocumentSessionQueueResult } from '../../lib/documentSessionQueue';
import type { DocumentAuthorityStatus, DocumentSessionState, WorkspaceIdentity } from '../../lib/documentSession';
import type { CrashDraftScheduler } from '../../lib/crashDrafts';
import type { FileVersion, WorkspaceFileEntry, WorkspaceSnapshot } from '../../types';
import type { AcceptedActiveDocumentWatch, ExternalFileActionState, PendingDocumentSaveConflict } from './sessionTypes';

export interface ExternalChangesDeps {
  paneState: PaneReplicatedState;
  sessionQueue: ReturnType<typeof createDocumentSessionQueue>;
  activeDocumentWatchRef: RefObject<AcceptedActiveDocumentWatch | null>;
  activeDocumentWatchTransport: ActiveDocumentWatchTransport | null;
  activeFileVersionRef: RefObject<FileVersion | null>;
  activePath: string | null;
  activePathRef: RefObject<string | null>;
  advanceCrashDraftIdentity: (priorDocumentId: string) => void;
  applyDocumentSessionState: (next: DocumentSessionState) => void;
  applyWorkspaceSnapshot: (response: WorkspaceSnapshot) => void;
  authorityStatus: DocumentAuthorityStatus;
  crashDraftDocumentIdRef: RefObject<string>;
  crashDraftSchedulerRef: RefObject<CrashDraftScheduler | null>;
  currentDocumentSessionState: () => DocumentSessionState;
  documentGenerationRef: RefObject<number>;
  documentIdentity: { documentId: string; documentEpoch: number; };
  documentOpenRequestRef: RefObject<number>;
  executeSessionOperation: <T>(operation: DocumentSessionQueueOperation<T>) => Promise<DocumentSessionQueueResult<T> | null>;
  externalFileActionRef: RefObject<ExternalFileActionState | null>;
  files: WorkspaceFileEntry[];
  isPopout: boolean;
  localeRef: RefObject<EffectiveLocale>;
  ordinaryDocumentActionsBlocked: () => boolean;
  paneReplicationRef: RefObject<PaneReplication | null>;
  paneStateRef: RefObject<PaneReplicatedState>;
  popoutPane: "main" | "editor" | "preview";
  saveConflictRef: RefObject<PendingDocumentSaveConflict | null>;
  setContent: Dispatch<SetStateAction<string>>;
  setError: Dispatch<SetStateAction<string | null>>;
  setExternalFileAction: Dispatch<SetStateAction<ExternalFileActionState | null>>;
  setNotice: Dispatch<SetStateAction<string | null>>;
  setSaveConflictState: (next: PendingDocumentSaveConflict | null) => void;
  setWorkspaceRoot: Dispatch<SetStateAction<string | null>>;
  setWorkspaceSessionRestoreSettled: Dispatch<SetStateAction<boolean>>;
  workspaceFilesRef: RefObject<WorkspaceFileEntry[]>;
  workspaceGenerationRef: RefObject<number>;
  workspaceIdentityRef: RefObject<WorkspaceIdentity>;
  workspaceRoot: string | null;
  workspaceSessionPersistRevisionRef: RefObject<number>;
  workspaceSessionPersistTailRef: RefObject<Promise<void>>;
  workspaceSessionRestoreMountedRef: RefObject<boolean>;
  workspaceSessionRestoreSettled: boolean;
  workspaceSessionRestoreSettledRef: RefObject<boolean>;
}
