import type { Dispatch, RefObject, SetStateAction } from 'react';
import type { EffectiveLocale } from '../../lib/locale';
import type { PaneReplication, PaneReplicatedState } from '../../lib/paneSync';
import type { ActiveDocumentWatchEvent, ActiveDocumentWatchSnapshotEnvelope, ActiveDocumentWatchTransport } from '../../lib/activeDocumentWatch';
import type { DocumentSessionQueueOperation, DocumentSessionQueueResult } from '../../lib/documentSessionQueue';
import type { DocumentAuthorityStatus, DocumentSessionState, WorkspaceIdentity } from '../../lib/documentSession';
import type { ExternalDocumentChangeDecision } from '../../lib/externalDocumentChange';
import type { CrashDraftScheduler } from '../../lib/crashDrafts';
import type { OpenIntentTargetKind } from '../../lib/openIntent';
import type { FileVersion, OpenFileResponse, PreparedOpenFileResponse, SnapshotReceipt, WorkspaceDirectoryEntry, WorkspaceFileEntry, WorkspaceFileKind, WorkspaceSnapshot } from '../../types';
import type { AcceptedActiveDocumentWatch, ActiveWorkspaceIdentity, ExternalFileActionState, PendingDocumentSaveConflict, PreparedOpenApplyResult } from './sessionTypes';

export interface SaveFlowDeps {
  ordinaryDocumentActionsBlocked: () => boolean;
  setSaveConflictState: (next: PendingDocumentSaveConflict | null) => void;
  lockDocumentAuthorityUnknown: () => void;
  activeDocumentWatchRef: RefObject<AcceptedActiveDocumentWatch | null>;
  activeDocumentWatchTransport: ActiveDocumentWatchTransport | null;
  activeFileKind: WorkspaceFileKind;
  activeFileVersionRef: RefObject<FileVersion | null>;
  activeMimeType: string | null;
  activePath: string | null;
  activePathRef: RefObject<string | null>;
  advanceCrashDraftIdentity: (priorDocumentId: string) => void;
  afterConfirmedSave: ((documentId: string) => boolean | void | Promise<boolean | void>) | undefined;
  applyDocumentSessionState: (next: DocumentSessionState) => void;
  applyExternalDocumentDecision: (decision: ExternalDocumentChangeDecision, sequence: number) => Promise<void>;
  applyOpenFileResponse: (response: OpenFileResponse) => void;
  applyPreparedOpen: (prepared: PreparedOpenFileResponse, requestedGeneration: number, reportFailure?: boolean, discardCurrentCrashDraft?: boolean) => Promise<PreparedOpenApplyResult>;
  applyWorkspaceSnapshot: (response: WorkspaceSnapshot) => void;
  authorityStatus: DocumentAuthorityStatus;
  broadcastPaneState: () => Promise<void>;
  busy: boolean;
  claimPreparedOpen: (prepared: PreparedOpenFileResponse | null, requestedGeneration: number) => number | null;
  cleanupConfirmedCrashDraft: (committedContent: string) => Promise<void>;
  content: string;
  crashDraftDocumentIdRef: RefObject<string>;
  crashDraftSchedulerRef: RefObject<CrashDraftScheduler | null>;
  currentDocumentSessionState: () => DocumentSessionState;
  directories: WorkspaceDirectoryEntry[];
  documentGenerationRef: RefObject<number>;
  documentIdentity: { documentId: string; documentEpoch: number; };
  documentOpenRequestRef: RefObject<number>;
  enqueueActiveDocumentWatchEnvelope: (accepted: AcceptedActiveDocumentWatch, envelope: ActiveDocumentWatchSnapshotEnvelope, registration?: boolean) => Promise<boolean>;
  enqueueActiveDocumentWatchHealth: (accepted: AcceptedActiveDocumentWatch, event: ActiveDocumentWatchEvent & { event: { kind: "health"; }; }) => Promise<void>;
  envelopeMatchesAcceptedPath: (accepted: AcceptedActiveDocumentWatch, envelope: ActiveDocumentWatchSnapshotEnvelope) => boolean;
  error: string | null;
  executeSessionOperation: <T>(operation: DocumentSessionQueueOperation<T>) => Promise<DocumentSessionQueueResult<T> | null>;
  externalFileActionRef: RefObject<ExternalFileActionState | null>;
  files: WorkspaceFileEntry[];
  flushWorkspaceSession: () => Promise<void>;
  getActiveWorkspace: () => ActiveWorkspaceIdentity | null;
  handleActiveDocumentWatchEvent: (event: ActiveDocumentWatchEvent) => void;
  handleClearRecent: () => Promise<void>;
  handleOpenDirectory: () => Promise<void>;
  handleOpenFile: () => Promise<void>;
  handleOpenRecent: (entryId: string) => Promise<void>;
  isAcceptedWatchCurrent: (accepted: AcceptedActiveDocumentWatch, sequence?: number) => boolean;
  isCurrentWorkspaceRequest: (requestedWorkspace: ActiveWorkspaceIdentity, requestedGeneration: number) => boolean;
  isPopout: boolean;
  lastSavedContent: string;
  localeRef: RefObject<EffectiveLocale>;
  openWorkspaceFilePath: (path: string) => Promise<void>;
  openWorkspaceIndexResult: (workspaceToken: string, workspaceRoot: string, indexGeneration: number, relativePath: string) => Promise<void>;
  paneReplicationRef: RefObject<PaneReplication | null>;
  paneStateRef: RefObject<PaneReplicatedState>;
  popoutPane: "main" | "editor" | "preview";
  previewRevision: number;
  reconcileRequestedWorkspaceReceipt: (requestedWorkspace: ActiveWorkspaceIdentity, requestedGeneration: number, receipt: SnapshotReceipt) => Promise<string | null>;
  refreshWorkspace: (root?: string) => Promise<void>;
  refreshWorkspaceAfterExternalPathChange: (previousPath: string) => Promise<void>;
  refreshWorkspaceDirect: (requestedWorkspace: ActiveWorkspaceIdentity, requestedGeneration: number) => Promise<void>;
  resolveOpenIntentRequest: (intentId: string, targetKind?: OpenIntentTargetKind, discardCurrentCrashDraft?: boolean) => Promise<"failed" | "blocked" | "accepted">;
  rollbackWorkspaceState: (prior: WorkspaceSnapshot | null) => void;
  saveConflictRef: RefObject<PendingDocumentSaveConflict | null>;
  setAuthorityStatus: Dispatch<SetStateAction<DocumentAuthorityStatus>>;
  setAutosaveBlockedContent: Dispatch<SetStateAction<string | null>>;
  setContent: Dispatch<SetStateAction<string>>;
  setError: Dispatch<SetStateAction<string | null>>;
  setExternalFileAction: Dispatch<SetStateAction<ExternalFileActionState | null>>;
  setExternalFileActionState: (next: ExternalFileActionState | null) => void;
  setLastSavedContent: Dispatch<SetStateAction<string>>;
  setNotice: Dispatch<SetStateAction<string | null>>;
  setSaveConflict: Dispatch<SetStateAction<PendingDocumentSaveConflict | null>>;
  setWorkspaceRoot: Dispatch<SetStateAction<string | null>>;
  setWorkspaceSessionRestoreSettled: Dispatch<SetStateAction<boolean>>;
  settleWorkspaceSessionRestore: () => void;
  stopAcceptedActiveDocumentWatch: () => Promise<void>;
  synchronizeWorkspaceForStandaloneFile: (path: string, requestedDocumentGeneration: number, intentId: string) => Promise<void>;
  workspaceDirectoriesRef: RefObject<WorkspaceDirectoryEntry[]>;
  workspaceFilesRef: RefObject<WorkspaceFileEntry[]>;
  workspaceGenerationRef: RefObject<number>;
  workspaceIdentityRef: RefObject<WorkspaceIdentity>;
  workspaceRoot: string | null;
  workspaceSessionPersistRevisionRef: RefObject<number>;
  workspaceSessionPersistTailRef: RefObject<Promise<void>>;
  workspaceSessionRestoreMountedRef: RefObject<boolean>;
  workspaceSessionRestoreSettled: boolean;
  workspaceSessionRestoreSettledRef: RefObject<boolean>;
}
