import type { SkinDefinition } from "../skinTypes";

export const qinghuaJilanSkin = {
  id: "qinghua-jilan",
  nameZh: "青花·苏青",
  nameEn: "Blue-and-White · Cobalt",
  appearance: "light",
  tokens: {
    background: "#e7ecf3",
    toolbar: "#f7f8fa",
    sidebar: "#eef1f5",
    panel: "#ffffff",
    panelMuted: "#f4f6f9",
    border: "#c6ccd5",
    borderStrong: "#a7b0bd",
    chromeText: "#1d2530",
    textReading: "#2a313a",
    textMuted: "#596779",
    textFaint: "#788392",
    accent: "#235ba8",
    accentHover: "#18467f",
    accentForeground: "#ffffff",
    themeEmphasis: "#235ba8",
    themeEmphasisForeground: "#ffffff",
    focusRing: "#4e7fbd",
    selectionMuted: "#dce6f4",
    selectionStrong: "#235ba8",
    selectionForeground: "#ffffff",
    scrollbarThumb: "#98a3b1",
    motif: "#52719b",
    shadow: "rgba(27, 38, 52, 0.2)",
    previewBg: "#ffffff",
    previewHeading: "#235ba8",
    previewHeadingSecondary: "#235ba8",
    previewQuoteBg: "#eef3f8",
    previewQuoteText: "#34485f",
    previewTableHead: "#eaf0f8",
    previewTableCell: "#fafbfd",
    codeBg: "#f4f6f9",
    codeBorder: "#d2d8e1",
    codeText: "#232b36",
    codeGutterText: "#2d648f",
    syntaxHeading: "#235ba8",
    syntaxStrong: "#875d18",
    syntaxEmphasis: "#73538a",
    syntaxLink: "#1f5da6",
    syntaxCode: "#9a2f38",
    syntaxCodeBg: "#faedef",
    syntaxQuote: "#3f705b",
    syntaxList: "#87631d",
    syntaxMeta: "#6d7482",
    syntaxComment: "#66717c",
  },
} as const satisfies SkinDefinition;
