import type { SkinDefinition } from "../skinTypes";

export const songkeZhuyingSkin = {
  id: "songke-zhuying",
  nameZh: "宋版·竹青",
  nameEn: "Song Edition · Bamboo Green",
  appearance: "light",
  tokens: {
    background: "#e6eadf",
    toolbar: "#f5f6f2",
    sidebar: "#edf0e9",
    panel: "#fefefc",
    panelMuted: "#f3f5f0",
    border: "#c5cbbf",
    borderStrong: "#a5aea0",
    chromeText: "#1f2721",
    textReading: "#2d322e",
    textMuted: "#5b655a",
    textFaint: "#788179",
    accent: "#526b3f",
    accentHover: "#3d542f",
    accentForeground: "#ffffff",
    themeEmphasis: "#526b3f",
    themeEmphasisForeground: "#ffffff",
    focusRing: "#71835b",
    selectionMuted: "#e0e8d8",
    selectionStrong: "#526b3f",
    selectionForeground: "#ffffff",
    scrollbarThumb: "#98a095",
    motif: "#6f8050",
    shadow: "rgba(31, 38, 32, 0.18)",
    previewBg: "#fefefc",
    previewHeading: "#526b3f",
    previewHeadingSecondary: "#526b3f",
    previewQuoteBg: "#eef2eb",
    previewQuoteText: "#38483c",
    previewTableHead: "#edf2ea",
    previewTableCell: "#fafbf8",
    codeBg: "#f4f5f1",
    codeBorder: "#d0d5cc",
    codeText: "#262b27",
    codeGutterText: "#61734d",
    syntaxHeading: "#526b3f",
    syntaxStrong: "#7b5b20",
    syntaxEmphasis: "#6f5577",
    syntaxLink: "#496238",
    syntaxCode: "#893730",
    syntaxCodeBg: "#f6ecea",
    syntaxQuote: "#596f49",
    syntaxList: "#73581e",
    syntaxMeta: "#696f69",
    syntaxComment: "#5b655a",
  },
} as const satisfies SkinDefinition;
