export type SettingsDialogText = typeof copy['en'];

export const copy = {
  en: {
    title: 'Settings', autosave: 'Autosave', autosaveDelay: 'Save delay', milliseconds: 'ms',
    autosaveMode: 'Trigger', autosaveModeAfterDelay: 'After a delay', autosaveModeOnFocusChange: 'When the editor loses focus', autosaveModeOnWindowChange: 'When the window loses focus',
    spellcheck: 'Spellcheck', wikilinks: 'Wikilinks', resources: 'Resource folder', layout: 'Editor width',
    appearance: 'Appearance', skin: 'Theme', followSystem: 'Follow system theme', language: 'Language',
    editorFontSize: 'Editor font size', fontSizeUnit: 'px',
    autosaveDelayInvalid: 'Save delay must be between 250 and 60000 ms.',
    fontSizeInvalid: 'Editor font size must be between 12 and 28 px.',
    save: 'Save', cancel: 'Cancel', reset: 'Reset Settings', retry: 'Try Again',
    recoveryTitle: 'Settings Could Not Be Loaded',
    recoveryMessage: 'The saved settings are unavailable or incompatible. Retry, or reset them to verified defaults.',
    futureTitle: 'Settings Require a Newer mdx Version',
    futureMessage: 'These settings were created by a newer version and were left unchanged. Upgrade mdx, then try again.',
    conflictTitle: 'Settings Changed Elsewhere',
    conflictMessage: 'Settings changed in another window. Reload the latest settings before making changes.',
    reload: 'Reload Settings',
    workspaceIndex: 'Workspace Index',
    workspaceIndexDescription: 'Manage the local index used to search workspace files.',
    workspaceIndexUnavailable: 'Open a workspace to manage its index.',
    discardIndex: 'Discard index',
    rebuildIndex: 'Rebuild index',
    chooseResources: 'Choose resource folder',
    shortcuts: 'Keyboard Shortcuts', resetShortcuts: 'Restore shortcut defaults',
    shortcutConflict: 'Shortcut conflict', shortcutInvalid: 'Enter a supported shortcut.',
    shortcutLabels: { save: 'Save', saveAs: 'Save as', quickOpen: 'Quick open', workspaceSearch: 'Workspace search', export: 'Export', settings: 'Settings', editorFontLarger: 'Increase editor font', editorFontSmaller: 'Decrease editor font', editorFontReset: 'Reset editor font' },
  },
  'zh-CN': {
    title: '设置', autosave: '自动保存', autosaveDelay: '保存延迟', milliseconds: '毫秒',
    autosaveMode: '触发方式', autosaveModeAfterDelay: '延迟后保存', autosaveModeOnFocusChange: '编辑器失焦时', autosaveModeOnWindowChange: '窗口失焦时',
    spellcheck: '拼写检查', wikilinks: '双向链接', resources: '资源文件夹', layout: '编辑区宽度',
    appearance: '外观', skin: '主题', followSystem: '跟随系统主题', language: '语言',
    editorFontSize: '编辑器字号', fontSizeUnit: 'px',
    autosaveDelayInvalid: '保存延迟需在 250 到 60000 毫秒之间。',
    fontSizeInvalid: '编辑器字号需在 12 到 28 px 之间。',
    save: '保存', cancel: '取消', reset: '重置设置', retry: '重试',
    recoveryTitle: '无法加载设置',
    recoveryMessage: '已保存的设置不可用或不兼容。请重试，或将设置重置为已验证的默认值。',
    futureTitle: '设置需要更新版本的 mdx',
    futureMessage: '这些设置由更新版本创建，文件未被修改。请升级 mdx 后重试。',
    conflictTitle: '设置已在其他窗口更改',
    conflictMessage: '设置已在其他窗口更新。请先重新加载最新设置，再继续修改。',
    reload: '重新加载设置',
    workspaceIndex: '工作区索引',
    workspaceIndexDescription: '管理用于搜索工作区文件的本地索引。',
    workspaceIndexUnavailable: '请先打开工作区，再管理其索引。',
    discardIndex: '丢弃索引',
    rebuildIndex: '重建索引',
    chooseResources: '选择资源文件夹',
    shortcuts: '键盘快捷键', resetShortcuts: '恢复默认快捷键',
    shortcutConflict: '快捷键冲突', shortcutInvalid: '请输入受支持的快捷键。',
    shortcutLabels: { save: '保存', saveAs: '另存为', quickOpen: '快速打开', workspaceSearch: '工作区搜索', export: '导出', settings: '设置', editorFontLarger: '放大编辑器字号', editorFontSmaller: '缩小编辑器字号', editorFontReset: '重置编辑器字号' },
  },
};
